name: 'My First GitHub Actons'

on: push

env:
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
      - name: Mask output value
        id: first
        shell: bash
        run: |
          value1='This is the super secret value'

          echo "::add-mask::$value1"
          echo "::set-output name=first_value::$value1"

      - name: Check output value
        shell: bash
        run: |
          echo "value: ${{ steps.first.outputs.first_value }}"

      - name: Check GitHub Secrets 2
        shell: bash
        run: |
          echo "secret: ${{ secrets.HELLO }}"

      - name: Check GitHub Secrets
        shell: pwsh
        run: |
          if ("${{ secrets.HELLO }})" -eq "WORLD") {
            echo "YES!"
          } else {
            echo "NO!"
          }